### ISSUE TITLE
General TO-DO List

### ISSUE THREAD

**Issue by ForMyFreedom** [ForMyFreedom/NewEraRPGPlataform#12]
- [x] Area to Active Effects (Call atention to see and remove when desactivate. Like 'Create Technique or Critic Use from {Work}' too!!)
 - [x] Custom roll button (I think i should be put in the place of the 'Sheet Button')
 - [x] Do the Maestry Path in Works
 - [ ] Clean the code to solve dependences
 - [ ] Make the data pass be 'null friendly' to evade bugs
 - [x] Implement RD to be considered in the Apply Life Button if the user activated [Create as Booble, turn ModApply to only positive modify]
 - [x] Change the Works Path to adquate the new evolution (Critic each 10, Tech each 20)
 - [ ] Make Work a NotificationConsumer to make the Atribute evolution each 5 be maded by a notification alerting, that when close, give the point

**Comment by ForMyFreedom** [comment]
Some problem with the 'Atribute' make me change the name to portuguese... solve this latter

**Comment by ForMyFreedom** [comment]
- [x] Ways of calculate Skill (Manual - Half of Work)

**Comment by ForMyFreedom** [comment]
- [ ] Create a Button (Below of Notification Bell) to apply Turn Effect (Entry, Out, *Disable)
- [ ] Find a way to block a critic to be activated if it's on hold [Like in techniques and regular use of critic]

**Comment by ForMyFreedom** [comment]
- [ ] Implement Support in techniques
